<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class ModuleTableSeeder extends Seeder
{
    public function run()
    {

        DB::table('module')->insert([
            'varTitle'        => 'Front Home',
            'varModuleName'   => 'home',
            'varTableName'    => '',
            'varModelName'    => '',
            'varModuleClass'  => 'HomeController',
            'intDisplayOrder' => 1,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'N',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => '',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Menu',
            'varModuleName'   => 'menu',
            'varTableName'    => 'menu',
            'varModelName'    => 'Menu',
            'varModuleClass'  => 'MenuController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 3.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Staticblocks',
            'varModuleName'   => 'static-block',
            'varTableName'    => 'static_block',
            'varModelName'    => 'StaticBlocks',
            'varModuleClass'  => 'StaticBlocksController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'PopUp',
            'varModuleName'   => 'popup',
            'varTableName'    => 'pop_up_content',
            'varModelName'    => 'PopUpContent',
            'varModuleClass'  => 'PopupController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Sitemap',
            'varModuleName'   => 'sitemap',
            'varTableName'    => '',
            'varModelName'    => '',
            'varModuleClass'  => '',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'menu-type',
            'varModuleName'   => 'menu-type',
            'varTableName'    => 'menu_type',
            'varModelName'    => 'MenuType',
            'varModuleClass'  => '',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Email Log',
            'varModuleName'   => 'email-log',
            'varTableName'    => 'email_log',
            'varModelName'    => 'EmailLog',
            'varModuleClass'  => 'EmailLogController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list,delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'log',
            'varModuleName'   => 'log',
            'varTableName'    => 'log',
            'varModelName'    => 'Log',
            'varModuleClass'  => 'LogController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete, advanced',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Project Category',
            'varModuleName'   => 'project-category',
            'varTableName'    => 'project_category',
            'varModelName'    => 'ProjectCategory',
            'varModuleClass'  => 'ProjectCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Banners',
            'varModuleName'   => 'banners',
            'varTableName'    => 'banner',
            'varModelName'    => 'Banner',
            'varModuleClass'  => 'BannerController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Inner Banner',
            'varModuleName'   => 'inner-banner',
            'varTableName'    => 'inner_banner',
            'varModelName'    => 'InnerBanner',
            'varModuleClass'  => 'InnerBannerController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Blogs',
            'varModuleName'   => 'blogs',
            'varTableName'    => 'blog',
            'varModelName'    => 'Blogs',
            'varModuleClass'  => 'BlogsController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Contact Us',
            'varModuleName'   => 'contact-us',
            'varTableName'    => 'contact_lead',
            'varModelName'    => 'ContactLead',
            'varModuleClass'  => 'ContactleadController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 2.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'FAQ',
            'varModuleName'   => 'faq',
            'varTableName'    => 'faq',
            'varModelName'    => 'Faq',
            'varModuleClass'  => 'FaqController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 2.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Services',
            'varModuleName'   => 'services',
            'varTableName'    => 'services',
            'varModelName'    => 'Services',
            'varModuleClass'  => 'ServicesController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Testimonials',
            'varModuleName'   => 'testimonial',
            'varTableName'    => 'testimonials',
            'varModelName'    => 'Testimonial',
            'varModuleClass'  => 'TestimonialController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Team',
            'varModuleName'   => 'team',
            'varTableName'    => 'team',
            'varModelName'    => 'Team',
            'varModuleClass'  => 'TeamController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 2.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Pages',
            'varModuleName'   => 'pages',
            'varTableName'    => 'cms_page',
            'varModelName'    => 'CmsPage',
            'varModuleClass'  => 'CmsPagesController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'News Letter',
            'varModuleName'   => 'newsletter-lead',
            'varTableName'    => 'newsletter_lead',
            'varModelName'    => 'NewsletterLead',
            'varModuleClass'  => 'NewsletterController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => '',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Contact Info',
            'varModuleName'   => 'contact-info',
            'varTableName'    => 'contact_info',
            'varModelName'    => 'ContactInfo',
            'varModuleClass'  => 'ContactInfoController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'News',
            'varModuleName'   => 'news',
            'varTableName'    => 'news',
            'varModelName'    => 'News',
            'varModuleClass'  => 'NewsController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Photo Album',
            'varModuleName'   => 'photo-album',
            'varTableName'    => 'photo_album',
            'varModelName'    => 'PhotoAlbum',
            'varModuleClass'  => 'PhotoAlbumController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Photo Gallery',
            'varModuleName'   => 'photo-gallery',
            'varTableName'    => 'photo_gallery',
            'varModelName'    => 'PhotoGallery',
            'varModuleClass'  => 'PhotoGalleryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'News Category',
            'varModuleName'   => 'news-category',
            'varTableName'    => 'news_category',
            'varModelName'    => 'NewsCategory',
            'varModuleClass'  => 'NewsCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Video Album',
            'varModuleName'   => 'video-album',
            'varTableName'    => 'video_album',
            'varModelName'    => 'VideoAlbum',
            'varModuleClass'  => 'VideoAlbumController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Video Gallery',
            'varModuleName'   => 'video-gallery',
            'varTableName'    => 'video_gallery',
            'varModelName'    => 'VideoGallery',
            'varModuleClass'  => 'VideoGalleryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Services Category',
            'varModuleName'   => 'service-category',
            'varTableName'    => 'service_category',
            'varModelName'    => 'ServiceCategory',
            'varModuleClass'  => 'ServiceCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Sponsors',
            'varModuleName'   => 'sponsor',
            'varTableName'    => 'sponsor',
            'varModelName'    => 'Sponsor',
            'varModuleClass'  => 'SponsorController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Blog Category',
            'varModuleName'   => 'blog-category',
            'varTableName'    => 'blog_category',
            'varModelName'    => 'BlogCategory',
            'varModuleClass'  => 'BlogCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Events',
            'varModuleName'   => 'events',
            'varTableName'    => 'event',
            'varModelName'    => 'Events',
            'varModuleClass'  => 'EventsController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Shows Category',
            'varModuleName'   => 'show-category',
            'varTableName'    => 'show_category',
            'varModelName'    => 'ShowCategory',
            'varModuleClass'  => 'ShowCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Product Category',
            'varModuleName'   => 'product-category',
            'varTableName'    => 'product_category',
            'varModelName'    => 'ProductCategory',
            'varModuleClass'  => 'ProductCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Products',
            'varModuleName'   => 'products',
            'varTableName'    => 'products',
            'varModelName'    => 'Products',
            'varModuleClass'  => 'ProductsController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Shows',
            'varModuleName'   => 'shows',
            'varTableName'    => 'show',
            'varModelName'    => 'Show',
            'varModuleClass'  => 'ShowController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Advertise',
            'varModuleName'   => 'advertise',
            'varTableName'    => 'advertises',
            'varModelName'    => 'Advertise',
            'varModuleClass'  => 'AdvertiseController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'N',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Careers',
            'varModuleName'   => 'careers',
            'varTableName'    => 'careers',
            'varModelName'    => 'Careers',
            'varModuleClass'  => 'CareersController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Careers Category',
            'varModuleName'   => 'careers-category',
            'varTableName'    => 'careers_category',
            'varModelName'    => 'CareersCategory',
            'varModuleClass'  => 'CareersCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Sponsor Category',
            'varModuleName'   => 'sponsor-category',
            'varTableName'    => 'sponsor_category',
            'varModelName'    => 'SponsorCategory',
            'varModuleClass'  => 'SponsorCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Event Category',
            'varModuleName'   => 'event-category',
            'varTableName'    => 'event_category',
            'varModelName'    => 'EventCategory',
            'varModuleClass'  => 'EventCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Client',
            'varModuleName'   => 'client',
            'varTableName'    => 'client',
            'varModelName'    => 'Client',
            'varModuleClass'  => 'ClientController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Client Category',
            'varModuleName'   => 'client-category',
            'varTableName'    => 'client_category',
            'varModelName'    => 'ClientCategory',
            'varModuleClass'  => 'ClientCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Restaurant Menu Category',
            'varModuleName'   => 'restaurant-menu-category',
            'varTableName'    => 'restaurant_menu_category',
            'varModelName'    => 'RestaurantMenuCategory',
            'varModuleClass'  => 'RestaurantMenuCategoryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Restaurant Reservations',
            'varModuleName'   => 'restaurant-reservations',
            'varTableName'    => 'restaurant_reservations_lead',
            'varModelName'    => 'RestaurantReservations',
            'varModuleClass'  => 'RestaurantReservationsController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Restaurant Menu',
            'varModuleName'   => 'restaurant-menu',
            'varTableName'    => 'restaurant_menu_items',
            'varModelName'    => 'RestaurantMenu',
            'varModuleClass'  => 'RestaurantMenuController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Book Appointment',
            'varModuleName'   => 'appointment-lead',
            'varTableName'    => 'appointment_lead',
            'varModelName'    => 'AppointmentLead',
            'varModuleClass'  => 'AppointmentleadController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Gallery',
            'varModuleName'   => 'gallery',
            'varTableName'    => 'gallery',
            'varModelName'    => 'Gallery',
            'varModuleClass'  => 'GalleryController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Projects',
            'varModuleName'   => 'projects',
            'varTableName'    => 'projects',
            'varModelName'    => 'Projects',
            'varModuleClass'  => 'ProjectController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Users',
            'varModuleName'   => 'users',
            'varTableName'    => 'users',
            'varModelName'    => 'User',
            'varModuleClass'  => 'UserController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Role',
            'varModuleName'   => 'roles',
            'varTableName'    => 'roles',
            'varModelName'    => 'Role',
            'varModuleClass'  => 'RoleController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, create, edit, delete, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Profile',
            'varModuleName'   => 'changeprofile',
            'varTableName'    => 'users',
            'varModelName'    => 'User',
            'varModuleClass'  => 'ProfileController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'edit, change-password',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'General Setting',
            'varModuleName'   => 'settings',
            'varTableName'    => 'general_setting',
            'varModelName'    => 'GeneralSettings',
            'varModuleClass'  => 'SettingsController',
            'intDisplayOrder' => 0,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'general-setting-management, smtp-mail-setting, seo-setting, social-setting, social-media-share-setting, other-setting, maintenance-setting, recent-activities, module-setting',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Login history',
            'varModuleName'   => 'login-history',
            'varTableName'    => 'login_history',
            'varModelName'    => 'LoginLog',
            'varModuleClass'  => 'LoginHistoryController',
            'intDisplayOrder' => 61,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Modules',
            'varModuleName'   => 'modules',
            'varTableName'    => 'module',
            'varModelName'    => 'Modules',
            'varModuleClass'  => 'ModuleBuilderController',
            'intDisplayOrder' => 62,
            'chrIsFront'      => 'N',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete, create, edit, publish',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

        DB::table('module')->insert([
            'varTitle'        => 'Privacy Removal Leads',
            'varModuleName'   => 'privacy-removal-leads',
            'varTableName'    => 'privacy_removal_leads',
            'varModelName'    => 'PrivacyRemovalLead',
            'varModuleClass'  => 'PrivacyRemovalLeadsController',
            'intDisplayOrder' => 63,
            'chrIsFront'      => 'Y',
            'chrIsPowerpanel' => 'Y',
            'chrIsGenerated'  => 'N',
            'decVersion'      => 1.0,
            'chrPublish'      => 'Y',
            'chrDelete'       => 'N',
            'varPermissions'  => 'list, delete',
            'created_at'      => Carbon::now(),
            'updated_at'      => Carbon::now(),
        ]);

    }
}
